language: objective-c
osx_image: xcode8.1
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap
script:
  # - set -o pipefail && xcodebuild test -workspace TySimulator.xcworkspace -scheme TySimulator ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -workspace TySimulator.xcworkspace -scheme TySimulator -sdk macosx ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES test
after_success:
  - bash <(curl -s https://codecov.io/bash) -cF osx
