language: objective-c
osx_image: xcode8.1
script:
  - set -o pipefail && xcodebuild test -workspace TySimulator.xcworkspace -scheme TySimulator ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN
